import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { useSession, signIn, signOut } from 'next-auth/react'
import LogIn from '../components/LogIn'
import SideBar from '../components/SideBar'
import Feed from '../components/Feed'


export default function Home() {
  const {data: session} = useSession()
  if(!session){
    return(
      <LogIn/>
    )
  }
  
  return (
    <div className='overflow-hidden h-screen bg-gray-100'>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='flex justify-center'>
        <SideBar/>
        <Feed/>
        {/* widgets */}
      </main>

    </div>
  )
}
