import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { getSession } from 'next-auth/react'
import LogIn from '../components/LogIn'


export default function Home({session}) {
  if(!session) <LogIn/>
  console.log(session)
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        {/* sidebar */}
        {/* feed */}
        {/* widgets */}
      </main>

    </div>
  )
}

export async function getServerSideProps(context){
  const session = await getSession(context)
  return {
    props:{
      session
    }
  }

}